### ISSUE TITLE
Ensure binary compatibility of upcoming release with previous minor releases

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2143]
Some of the changes to the Models utility introduced by #2056 are not binary compatible with RDF4J 3.1. In particular, the change of method param types from `Model` to `Iterable<Statement>` is not. This makes it impossible to run existing projects against a new version of RDF4J without being forced to recompile.

Although we have not made an explicit commitment to binary compatibility before it has been somewhat implied by our adherence to semantic versioning and claiming that minor versions are "fully backward compatible". I'll look at reactivating the japicmp plugin with potentially letting it fail the build. As a short term fix for this particular problem I will re-introduce the old method signatures with suitable javadoc annotations.

**Comment by jetztgradnet** [comment]
This change would be source compatible, but not binary compatible as the signature is part of the compiled byte code. Any re-compile will pick up the new signature, but anything already compiled will fail with a `NoSuchMethodError`...

**Comment by jeenbroekstra** [comment]
Generalizing this task a bit because I've detected some other compatibility issues.
